#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, BlueCat Networks
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""Ansible DHCP Address Pool module.

Part of the Men&Mice Ansible integration

Module to manage DHCP address pools in Micetro
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
  module: dhcpaddresspool
  short_description: Manage DHCP address pool(s) in the Micetro
  author:
    - BlueCat Networks
  version_added: "1.0.15"
  description:
    - Create/delete DHCP address pool(s) in Micetro.
    - A DHCP address pool is a sub-range of addresses within a DHCP
      scope, identified by its start and end address. The pool's C(name)
      is read-only and auto-generated by Micetro from that range
      (confirmed live: the API rejects any attempt to set it, on create
      or update, with "Property \"name\" is read-only").
  notes:
    - When in check mode, this module pretends to have done things
      and returns C(changed = True).
  options:
    state:
      description: The state of the DHCP address pool
      type: str
      choices: [ absent, present ]
      default: present
    dhcp_scope_ref:
      description: Reference of the DHCP scope that owns this address pool
      type: str
      required: true
    from_address:
      description: The start address of the DHCP address pool
      type: str
      required: true
    to_address:
      description: The end address of the DHCP address pool
      type: str
      required: true
    save_comment:
      description: Save comment left in Micetro
      type: str
      default: Ansible API
    mm_provider:
      description: Definition of the Micetro API mm_provider.
      type: dict
      required: true
      suboptions:
        mm_url:
          description: Men&Mice API server to connect to.
          type: str
          required: true
        mm_user:
          type: str
          description: userid to login with into the API.
          required: true
        mm_password:
          type: str
          description: password to login with into the API.
          required: true
"""

EXAMPLES = r"""
- name: Manage a DHCP address pool
  menandmice.ansible_micetro.dhcpaddresspool:
    dhcp_scope_ref: dhcpScopes/1
    from_address: 172.16.17.100
    to_address: 172.16.17.150
    mm_provider:
      mm_url: http://micetro.example.net
      mm_user: apiuser
      mm_password: apipasswd
  delegate_to: localhost

- name: Remove a DHCP address pool
  menandmice.ansible_micetro.dhcpaddresspool:
    state: absent
    dhcp_scope_ref: dhcpScopes/1
    from_address: 172.16.17.100
    to_address: 172.16.17.150
    mm_provider:
      mm_url: http://micetro.example.net
      mm_user: apiuser
      mm_password: apipasswd
  delegate_to: localhost
"""

RETURN = r"""
message:
    description: The output message from Micetro.
    type: str
    returned: always
"""

# All imports
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.menandmice.ansible_micetro.plugins.module_utils.micetro import (
    doapi,
    get_single_refs,
)


def run_module():
    """Run Ansible module."""
    # Define available arguments/parameters a user can pass to the module
    module_args = dict(
        state=dict(
            type="str",
            required=False,
            default="present",
            choices=["absent", "present"],
        ),
        dhcp_scope_ref=dict(type="str", required=True),
        from_address=dict(type="str", required=True),
        to_address=dict(type="str", required=True),
        save_comment=dict(type="str", required=False, default="Ansible API"),
        mm_provider=dict(
            type="dict",
            required=True,
            options=dict(
                mm_url=dict(type="str", required=True, no_log=False),
                mm_user=dict(type="str", required=True, no_log=False),
                mm_password=dict(type="str", required=True, no_log=True),
            ),
        ),
    )

    # Seed the result dict in the object
    # We primarily care about changed and state
    # change is if this module effectively modified the target
    # state will include any data that you want your module to pass back
    # for consumption, for example, in a subsequent task
    result = {
        "changed": False,
        "message": "No changes to DHCP address pool required",
    }

    # The AnsibleModule object will be our abstraction working with Ansible
    # this includes instantiation, a couple of common attr would be the
    # args/params passed to the execution, as well as if the module
    # supports check mode
    module = AnsibleModule(argument_spec=module_args, supports_check_mode=True)

    # If the user is working with this module in only check mode we do not
    # want to make any changes to the environment, just return the current
    # state with no modifications
    if module.check_mode:
        module.exit_json(**result)

    # Gather all module parameters
    mm_provider = module.params["mm_provider"]
    state = module.params["state"]
    dhcp_scope_ref = module.params["dhcp_scope_ref"]
    from_address = module.params["from_address"]
    to_address = module.params["to_address"]
    save_comment = module.params["save_comment"]

    # Ensure the DHCP scope reference is present
    resp = get_single_refs(dhcp_scope_ref, mm_provider)
    if resp.get("invalid", None):
        module.fail_json(
            msg="DHCP scope reference not found, please try again",
            dhcp_scope_ref=dhcp_scope_ref,
            response=resp,
        )

    # Find the address pool amongst the scope's pools. An address pool
    # is identified by its address range - its name is read-only and
    # auto-generated by Micetro, so it can't be used to look one up.
    resp = get_single_refs("%s/dhcpAddressPools" % dhcp_scope_ref, mm_provider)
    if resp.get("invalid", None):
        module.fail_json(
            msg="An error occurred, please try again", response=resp
        )

    pool = None
    for candidate in resp["dhcpAddressPools"]:
        if candidate["from"] == from_address and candidate["to"] == to_address:
            pool = candidate
            break

    # Ensure DHCP address pool is present
    if state == "present":
        if pool is None:
            # Create the DHCP address pool. Only "from"/"to" are
            # accepted here - "dhcpScopeRef" is implied by the URL, and
            # "name" is a read-only, server-generated property; sending
            # either one back on create makes the API reject the whole
            # request with a generic "Invalid address pool" error.
            url = "%s/dhcpAddressPools" % dhcp_scope_ref
            http_method = "POST"
            databody = {
                "dhcpAddressPool": {
                    "from": from_address,
                    "to": to_address,
                },
                "saveComment": save_comment,
            }

            api_result = doapi(url, http_method, mm_provider, databody)
            if api_result.get("warnings", None):
                module.fail_json(
                    msg="Failed to create DHCP address pool, please try again",
                    response=api_result,
                )

            if api_result["changed"]:
                result.update(
                    {
                        "changed": True,
                        "message": "DHCP address pool successfully created",
                    }
                )
        else:
            result["message"] = "DHCP address pool is present"

    # Ensure DHCP address pool is absent
    if state == "absent":
        if pool is None:
            result["message"] = "DHCP address pool is absent"
        else:
            url = pool["ref"]
            http_method = "DELETE"
            api_result = doapi(
                url, http_method, mm_provider, {"saveComment": save_comment}
            )
            if api_result["changed"]:
                result.update(
                    {
                        "changed": True,
                        "message": "DHCP address pool successfully removed",
                    }
                )

    # Return collected results
    module.exit_json(**result)


def main():
    run_module()


if __name__ == "__main__":
    main()
